# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
---
APPLY_FIXES: all
ENABLE: [BASH, JSON, MARKDOWN, YAML]
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: true
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
BASH_EXEC_FILE_EXTENSIONS: [".sh", ".bash", ".dash", ".ksh", ".zsh"]
BASH_SHELLCHECK_FILE_EXTENSIONS: [".sh", ".bash", ".dash", ".ksh", ".zsh"]
BASH_SHFMT_FILE_EXTENSIONS: [".sh", ".bash", ".dash", ".ksh", ".zsh"]
BASH_SHFMT_ARGUMENTS: "-i 4"
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
