# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# See config options - https://starship.rs/config/

add_newline = false
command_timeout = 800

# Left prompt (p10k: os_icon, dir, vcs, prompt_char)
format = """
$os$directory$git_branch$git_status$character
"""

[character]
success_symbol = "[❯](#5fd700)"
error_symbol   = "[❯](#ff0000)"
vicmd_symbol   = "[❮](#00afff)"
format = "$symbol "

[directory]
style = "bold #0087af"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = ".../"
read_only = "\uf023"
home_symbol = "~"
read_only_style = "#8787af"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "\uF126 "
style = "#5fd700"
truncation_length = 20
format = "on [$symbol$branch]($style) "