tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

cask "bitwarden"
cask "gimp"
cask "iterm2"
cask "obsidian"
cask "vlc"

cask "brave-browser"
cask "the-unarchiver"